### ISSUE TITLE
Identificar el Modelo de Servicio adecuado

### ISSUE THREAD

**Issue by toninavhd** [toninavhd/1-DAW_pt2#3]

**Comment by modiael** [comment]
¿Dónde está la decisión del modelo a elegir? Pongan comentarios aqui y resuelvan la issue en una rama vinculandole esta issue para que se cierre sola al aceptar la PR como aparece en esta [documentación ](https://docs.github.com/es/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue)
