### ISSUE TITLE
Análisis económico

### ISSUE THREAD

**Issue by toninavhd** [toninavhd/1-DAW_pt2#5]

**Comment by modiael** [comment]
Lo mismo, sólo se puede hacer el análisis económico tras elegir las plataformas que ofrecen el modelo que seleccionaron como adecuado para el supuesto. Asignen participantes a las issues para que sepan quien debe realizar qué tarea

**Comment by toninavhd** [comment]
Esta elegido y estamos en ello puedes ver lo que tenemos hecho por ahora en el README.  Adjunto el enlace por si no estamos viendo lo mismo https://github.com/toninavhd/1-DAW_pt2/blob/main/DJK/trabajo_grupo/README.md

**Comment by modiael** [comment]
Visto. Supongo entonces que están ahora haciendo el análisis económico? Asignense, pongan el issue en proceso y creen una rama para esta issue. Y cuando hagan la PR mencionen la issue esta haciendo uso de las palabras reservadas para que se cierre automáticamente al aprobar la PR como aparece en esta [documentación](https://docs.github.com/es/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue) que es la forma que expliqué en clase de cómo debemos trabajar.
